app:
  email-verification-url: "http://localhost:8080/verify-email?token="
  mailjet:
    apiKey: "${MAILJET_API_KEY}"
    secretKey: "${MAILJET_SECRET_KEY}"
    fromEmail: "${FROM_EMAIL}"
    fromName: "${FROM_NAME}"
spring:
  application:
    name: "Accounts-Server"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydatabase"
    username: "myuser"
    password: "mypassword"
logging:
  level:
    org.flywaydb: DEBUG